name: Bachelor
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cuda-cccl=12.4.127
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-opencl-dev=12.4.127
  - cuda-profiler-api=12.4.127
  - cuda-runtime=12.1.0
  - curl=7.55.1
  - double-conversion=3.1.5
  - eigen=3.4.0
  - expat=2.6.3
  - ffmpeg=4.2.2
  - fftw=3.3.10
  - filelock=3.13.1
  - freetype=2.12.1
  - gl2ps=1.4.2
  - glew=2.2.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmpy2=2.1.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - jsoncpp=1.9.4
  - krb5=1.21.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.1.3
  - libclang=12.0.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcurl=8.8.0
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.12
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libitk=5.2.1
  - libitk-devel=5.2.1
  - libjpeg-turbo=2.0.0
  - libnetcdf=4.8.1
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libogg=1.3.5
  - libpng=1.6.39
  - libssh2=1.11.0
  - libtheora=1.1.1
  - libtiff=4.4.0
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libzip=1.8.0
  - libzlib=1.2.13
  - loguru=0.5.3
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.0
  - openssl=3.3.2
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.2
  - proj=6.2.1
  - pysocks=1.7.1
  - python=3.10.14
  - python_abi=3.10
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - qt=5.15.7
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - requests=2.32.3
  - setuptools=72.1.0
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - tbb-devel=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.11.0
  - ucrt=10.0.22621.0
  - urllib3=2.2.2
  - utfcpp=3.2.1
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - vtk=9.0.3
  - wheel=0.43.0
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - acvl-utils==0.2
      - argparse==1.4.0
      - batchgenerators==0.25
      - batchgeneratorsv2==0.2.1
      - connected-components-3d==3.18.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dataclasses==0.6
      - dicom2nifti==2.4.11
      - dill==0.3.8
      - dynamic-network-architectures==0.3.1
      - einops==0.8.0
      - fft-conv-pytorch==1.2.0
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - future==1.0.0
      - imagecodecs==2024.6.1
      - imageio==2.35.1
      - joblib==1.4.2
      - kiwisolver==1.4.6
      - lazy-loader==0.4
      - linecache2==1.0.0
      - matplotlib==3.9.2
      - multiprocess==0.70.16
      - nibabel==5.2.1
      - nnunetv2==2.5.1
      - opencv-python==4.10.0.84
      - p-tqdm==1.4.2
      - packaging==24.1
      - pandas==2.2.2
      - pathos==0.3.2
      - pox==0.3.4
      - ppft==1.7.6.8
      - pyarrow==17.0.0
      - pydicom==2.4.4
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-gdcm==3.0.24.1
      - python-graphviz==0.20.3
      - pytz==2024.1
      - rt-utils==1.2.7
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - simpleitk==2.4.0
      - six==1.16.0
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - totalsegmentator==2.4.0
      - tqdm==4.66.5
      - traceback2==1.4.0
      - tzdata==2024.1
      - unittest2==1.1.0
      - xvfbwrapper==0.2.9
      - yacs==0.1.8
